version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13701:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/db.sqlite
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_DISCORD_ID=${AUTH_DISCORD_ID}
      - AUTH_DISCORD_SECRET=${AUTH_DISCORD_SECRET}
      - UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
    volumes:
      # 将数据库文件映射到宿主机，实现数据持久化
      - ./data:/app/prisma
    restart: unless-stopped
